plugins {
    id 'com.android.library'
}


repositories {
    google()
    mavenCentral()
    jcenter() // For 'org.webrtc:google-webrtc:1.0.23995'
}

dependencies {

    implementation 'ch.acra:acra:4.9.0'
    implementation 'org.locationtech.jts:jts-core:1.16.1'
    implementation 'org.osmdroid:osmdroid-android:6.1.0'
    implementation 'redis.clients:jedis:3.1.0'
    implementation 'com.caverock:androidsvg:1.2.1'

    implementation 'com.firebase:firebase-client-android:2.5.2'
    implementation 'com.google.api-client:google-api-client:1.31.1'
    implementation 'com.google.api-client:google-api-client-android2:1.10.3-beta'
    implementation 'org.webrtc:google-webrtc:1.0.23995'

    implementation fileTree('libs')
    implementation project(':annotations')
}

configurations {
    all {
        exclude module: 'xpp3'
        exclude module: 'xmlParserAPIs'
        exclude module: 'opengl-api'
        exclude module: 'json'
        exclude module: 'commons-logging'
        exclude module: 'httpclient'
    }

    implementation {
        setCanBeResolved(true)
    }
}

task copyImpl(type: Copy) {
    from configurations.implementation
    into 'build/implementation'
}
